// <auto-generated />
using Exercice01_Adresses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercice01_Adresses.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230822074822_TablesAndColumnsNameChanged")]
    partial class TablesAndColumnsNameChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exercice01_Adresses.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("postal_code");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street_name");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int")
                        .HasColumnName("street_number");

                    b.HasKey("Id");

                    b.ToTable("addresse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Maz",
                            PostalCode = "62670",
                            StreetName = "rue de la sorbonne",
                            StreetNumber = 15
                        },
                        new
                        {
                            Id = 2,
                            City = "Paris",
                            PostalCode = "75000",
                            StreetName = "Avenue du poulet",
                            StreetNumber = 45
                        },
                        new
                        {
                            Id = 3,
                            City = "Marseille",
                            PostalCode = "13000",
                            StreetName = "rue Victor Hugo",
                            StreetNumber = 12
                        },
                        new
                        {
                            Id = 4,
                            City = "Lens",
                            PostalCode = "62800",
                            StreetName = "Boulevard des coqs",
                            StreetNumber = 22
                        },
                        new
                        {
                            Id = 5,
                            City = "Arras",
                            PostalCode = "62000",
                            StreetName = "rue du sapin",
                            StreetNumber = 15
                        },
                        new
                        {
                            Id = 6,
                            City = "Lille",
                            PostalCode = "59000",
                            StreetName = "rue des choux",
                            StreetNumber = 58
                        },
                        new
                        {
                            Id = 7,
                            City = "Maz",
                            PostalCode = "62670",
                            StreetName = "rue Vigny",
                            StreetNumber = 89
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
