// <auto-generated />
using Exercice02_Hotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercice02_Hotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230823093116_StatusEnum")]
    partial class StatusEnum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exercice02_Hotel.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Alberto",
                            Lastname = "Enrique",
                            Phone = "0612234578"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Marcel",
                            Lastname = "Patoulacy",
                            Phone = "1234567890"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Edwardo",
                            Lastname = "Sanchez",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Jane",
                            Lastname = "Doe",
                            Phone = "0689564578"
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "Sahra",
                            Lastname = "New",
                            Phone = "0789564512"
                        });
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.ReservationRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomId");

                    b.ToTable("ReservationsRooms");
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NumberOfBed")
                        .HasColumnType("int")
                        .HasColumnName("number_of_bed");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfBed = 2,
                            Price = 44.99m,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            NumberOfBed = 1,
                            Price = 31.99m,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            NumberOfBed = 1,
                            Price = 31.99m,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            NumberOfBed = 1,
                            Price = 31.99m,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            NumberOfBed = 1,
                            Price = 31.99m,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            NumberOfBed = 2,
                            Price = 44.99m,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            NumberOfBed = 2,
                            Price = 44.99m,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            NumberOfBed = 3,
                            Price = 64.99m,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.Reservation", b =>
                {
                    b.HasOne("Exercice02_Hotel.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.ReservationRoom", b =>
                {
                    b.HasOne("Exercice02_Hotel.Models.Reservation", "Reservation")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exercice02_Hotel.Models.Room", "Room")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.Reservation", b =>
                {
                    b.Navigation("ReservationRooms");
                });

            modelBuilder.Entity("Exercice02_Hotel.Models.Room", b =>
                {
                    b.Navigation("ReservationRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
